### ISSUE TITLE
Not working on the latest Minecolonies version

### ISSUE THREAD

**Issue by Mysterius** [uecasm/jadecolonies#1]
For some reason, the mod doesn't seem to work on the latest Minecolonies version.
My knowledge is extremely limited, but could it be related with the change in coremod naming in 1.1.431 ? (https://github.com/ldtteam/minecolonies/pull/9707)

Jadecolonies seems to be enabled in the modlist but doesn't work and there is no Jadecolonies category in the plugin options of Jade.

**Comment by Maypul** [comment]
Seems so, there is following error in the log:
[15:38:48] [Worker-ResourceReload-11/ERROR] [Jade/]: Error loading plugin at nz.co.mirality.jadecolonies.JadePlugin
java.lang.NoClassDefFoundError: com/minecolonies/coremod/tileentities/TileEntityDecorationController
	at nz.co.mirality.jadecolonies.minecolonies.MineColoniesPlugin.register(MineColoniesPlugin.java:19) ~[JadeColonies-1.19.2-1.0.1.jar%23580!/:1.0.1] {re:classloading}
	at nz.co.mirality.jadecolonies.JadePlugin.register(JadePlugin.java:21) ~[JadeColonies-1.19.2-1.0.1.jar%23580!/:1.0.1] {re:classloading}
	at snownee.jade.Jade.loadComplete(Jade.java:130) ~[Jade-1.19.1-forge-8.9.2.jar%23578!/:8.9.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.19.2-43.3.7.jar%23721!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:123) ~[fmlcore-1.19.2-43.3.7.jar%23720!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?] {re:mixin}
Caused by: java.lang.ClassNotFoundException: com.minecolonies.coremod.tileentities.TileEntityDecorationController
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	... 16 more

**Comment by uecasm** [comment]
Thanks for the report.  This is now fixed in 1.20.

However I can't yet fix it in 1.19, because the 1.19 build of Minecolonies itself failed (did not upload properly to their build system, and really shouldn't have even hit Curseforge).  As such, for now I recommend downgrading to minecolonies-1.19.2-1.1.429-RELEASE and #blameray.

**Comment by ghost** [comment]
All sources are aviable and it (on my first view) changed only from

packages com.minecolonies.coremod.*
to
packages com.minecolonies.core.*

between 429 and the latest beta 516 or 595 for 1.19.2
